/*---------------------------------------------------------------------------
 * This file is autogenerated file using huawei LCD parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * Parser location: vendor/huawei/chipset_common/devkit/lcdkit/tools 
 *---------------------------------------------------------------------------*/

#ifndef _LCDKIT_PANELS__H_
#define _LCDKIT_PANELS__H_


#include "v1_djn_ili9881c_5p99_720p_video.h"
#include "v1_hsd_hx8394f_5p99_720p_video.h"
#include "v1_auo_otm1911a_7p12_1080p_video.h"
#include "v1_ebbg_hx8399c_7p12_1080p_video.h"
#include "ares_al00_vb_djn_ili9881c_5p99_720p_video.h"
#include "ares_al00_vc_djn_ili9881c_5p99_720p_video.h"
#include "ares_al10_vc_djn_ili9881c_5p99_720p_video.h"
#include "ares_l22_va_djn_ili9881c_5p99_720p_video.h"
#include "ares_al00_vb_hsd_hx8394f_5p99_720p_video.h"
#include "ares_al00_vc_hsd_hx8394f_5p99_720p_video.h"
#include "ares_al10_vc_hsd_hx8394f_5p99_720p_video.h"
#include "ares_l22_va_hsd_hx8394f_5p99_720p_video.h"
#include "v1_inx_ili9881c_5p99_720p_video.h"
#include "ares_al00_vb_inx_ili9881c_5p99_720p_video.h"
#include "ares_al00_vc_inx_ili9881c_5p99_720p_video.h"
#include "ares_al10_vc_inx_ili9881c_5p99_720p_video.h"
#include "ares_l22_va_inx_ili9881c_5p99_720p_video.h"
#include "default_auo_otm1901a_5p2_1080p_video_default.h"
/*---------------------------------------------------------------------------*/
/* static panel selection variable                                           */
/*---------------------------------------------------------------------------*/
enum {
V1_DJN_ILI9881C_5P99_720P_VIDEO_PANEL,
V1_HSD_HX8394F_5P99_720P_VIDEO_PANEL,
V1_AUO_OTM1911A_7P12_1080P_VIDEO_PANEL,
V1_EBBG_HX8399C_7P12_1080P_VIDEO_PANEL,
ARES_AL00_VB_DJN_ILI9881C_5P99_720P_VIDEO_PANEL,
ARES_AL00_VC_DJN_ILI9881C_5P99_720P_VIDEO_PANEL,
ARES_AL10_VC_DJN_ILI9881C_5P99_720P_VIDEO_PANEL,
ARES_L22_VA_DJN_ILI9881C_5P99_720P_VIDEO_PANEL,
ARES_AL00_VB_HSD_HX8394F_5P99_720P_VIDEO_PANEL,
ARES_AL00_VC_HSD_HX8394F_5P99_720P_VIDEO_PANEL,
ARES_AL10_VC_HSD_HX8394F_5P99_720P_VIDEO_PANEL,
ARES_L22_VA_HSD_HX8394F_5P99_720P_VIDEO_PANEL,
V1_INX_ILI9881C_5P99_720P_VIDEO_PANEL,
ARES_AL00_VB_INX_ILI9881C_5P99_720P_VIDEO_PANEL,
ARES_AL00_VC_INX_ILI9881C_5P99_720P_VIDEO_PANEL,
ARES_AL10_VC_INX_ILI9881C_5P99_720P_VIDEO_PANEL,
ARES_L22_VA_INX_ILI9881C_5P99_720P_VIDEO_PANEL,
DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
INVALID_PANEL_ID,
};


/*---------------------------------------------------------------------------*/
/* static panel board mapping variable                                           */
/*---------------------------------------------------------------------------*/
struct lcdkit_board_map {
    uint16_t lcd_id;
    uint8_t gpio_id;
    uint16_t board_id;
};

static struct lcdkit_board_map lcdkit_map[] = {
    {V1_DJN_ILI9881C_5P99_720P_VIDEO_PANEL, 0x06, 8000},
    {V1_HSD_HX8394F_5P99_720P_VIDEO_PANEL, 0x02, 8000},
    {V1_AUO_OTM1911A_7P12_1080P_VIDEO_PANEL, 0x01, 8000},
    {V1_EBBG_HX8399C_7P12_1080P_VIDEO_PANEL, 0x05, 8000},
    {ARES_AL00_VB_DJN_ILI9881C_5P99_720P_VIDEO_PANEL, 0x06, 8001},
    {ARES_AL00_VC_DJN_ILI9881C_5P99_720P_VIDEO_PANEL, 0x06, 8002},
    {ARES_AL10_VC_DJN_ILI9881C_5P99_720P_VIDEO_PANEL, 0x06, 8003},
    {ARES_L22_VA_DJN_ILI9881C_5P99_720P_VIDEO_PANEL, 0x06, 8004},
    {ARES_AL00_VB_HSD_HX8394F_5P99_720P_VIDEO_PANEL, 0x02, 8001},
    {ARES_AL00_VC_HSD_HX8394F_5P99_720P_VIDEO_PANEL, 0x02, 8002},
    {ARES_AL10_VC_HSD_HX8394F_5P99_720P_VIDEO_PANEL, 0x02, 8003},
    {ARES_L22_VA_HSD_HX8394F_5P99_720P_VIDEO_PANEL, 0x02, 8004},
    {V1_INX_ILI9881C_5P99_720P_VIDEO_PANEL, 0x09, 8000},
    {ARES_AL00_VB_INX_ILI9881C_5P99_720P_VIDEO_PANEL, 0x09, 8001},
    {ARES_AL00_VC_INX_ILI9881C_5P99_720P_VIDEO_PANEL, 0x09, 8002},
    {ARES_AL10_VC_INX_ILI9881C_5P99_720P_VIDEO_PANEL, 0x09, 8003},
    {ARES_L22_VA_INX_ILI9881C_5P99_720P_VIDEO_PANEL, 0x09, 8004},
    {DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, 0x0A, 0},
};

static bool hw_init_panel_data(struct panel_struct *panelstruct,
            struct msm_panel_info *pinfo,
            struct mdss_dsi_phy_ctrl *phy_db,
            uint16_t panel_id)
{
    switch (panel_id) {
    case V1_DJN_ILI9881C_5P99_720P_VIDEO_PANEL:
        panelstruct->paneldata    = &v1_djn_ili9881c_5p99_720p_video_panel_data;
        panelstruct->panelres     = &v1_djn_ili9881c_5p99_720p_video_panel_res;
        panelstruct->color        = &v1_djn_ili9881c_5p99_720p_video_color;
        panelstruct->videopanel   = &v1_djn_ili9881c_5p99_720p_video_video_panel;
        panelstruct->commandpanel = &v1_djn_ili9881c_5p99_720p_video_command_panel;
        panelstruct->state        = &v1_djn_ili9881c_5p99_720p_video_state;
        panelstruct->laneconfig   = &v1_djn_ili9881c_5p99_720p_video_lane_config;
        panelstruct->paneltiminginfo    = &v1_djn_ili9881c_5p99_720p_video_timing_info;
        panelstruct->panelresetseq = &v1_djn_ili9881c_5p99_720p_video_reset_seq;
        panelstruct->backlightinfo = &v1_djn_ili9881c_5p99_720p_video_backlight;
        if(V1_DJN_ILI9881C_5P99_720P_VIDEO_BIAS_IC_ARRAY == 0)
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = v1_djn_ili9881c_5p99_720p_video_bias_ic_array;
        }
        panelstruct->lcd_bias_ic_info.num_of_lcd_bias_ic_list = V1_DJN_ILI9881C_5P99_720P_VIDEO_BIAS_IC_ARRAY;
        if(V1_DJN_ILI9881C_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY == 0)
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = v1_djn_ili9881c_5p99_720p_video_backlight_ic_array;
        }
        panelstruct->lcd_backlight_ic_info.num_of_lcd_backlight_ic_list = V1_DJN_ILI9881C_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY;
        pinfo->labibb = &v1_djn_ili9881c_5p99_720p_video_labibb;
        pinfo->mipi.panel_on_cmds  = v1_djn_ili9881c_5p99_720p_video_on_command;
        pinfo->mipi.num_of_panel_on_cmds = ARRAY_SIZE(v1_djn_ili9881c_5p99_720p_video_on_command);
        pinfo->mipi.panel_off_cmds  = v1_djn_ili9881c_5p99_720p_video_off_command;
        pinfo->mipi.num_of_panel_off_cmds = ARRAY_SIZE(v1_djn_ili9881c_5p99_720p_video_off_command);
        memcpy(phy_db->timing, v1_djn_ili9881c_5p99_720p_video_timings, sizeof(v1_djn_ili9881c_5p99_720p_video_timings));
        memcpy(panel_regulator_settings, v1_djn_ili9881c_5p99_720p_video_regulator_setting, sizeof(v1_djn_ili9881c_5p99_720p_video_regulator_setting));
        pinfo->pipe_type = v1_djn_ili9881c_5p99_720p_video_mdp_pipe_type;
        phy_db->pll_type = v1_djn_ili9881c_5p99_720p_video_dsi_pll_type;
        pinfo->mipi.signature = v1_djn_ili9881c_5p99_720p_video_mipi_signature;
        lcdkit_config.lcd_platform   = &v1_djn_ili9881c_5p99_720p_video_panel_platform_config;
        lcdkit_config.lcd_misc   = &v1_djn_ili9881c_5p99_720p_video_panel_misc_info;
        lcdkit_config.lcd_delay     = &v1_djn_ili9881c_5p99_720p_video_panel_delay_ctrl;
        pinfo->mipi.tx_eot_append = lcdkit_config.lcd_misc->tx_eot_append;
        pinfo->mipi.rx_eot_ignore = lcdkit_config.lcd_misc->rx_eot_ignore;
        phy_db->regulator_mode = lcdkit_config.lcd_misc->mipi_regulator_mode;
        lcdkit_config.backlight_cmds   = v1_djn_ili9881c_5p99_720p_video_backlight_command;
        lcdkit_config.num_of_backlight_cmds   = ARRAY_SIZE(v1_djn_ili9881c_5p99_720p_video_backlight_command);
        break;

    case V1_HSD_HX8394F_5P99_720P_VIDEO_PANEL:
        panelstruct->paneldata    = &v1_hsd_hx8394f_5p99_720p_video_panel_data;
        panelstruct->panelres     = &v1_hsd_hx8394f_5p99_720p_video_panel_res;
        panelstruct->color        = &v1_hsd_hx8394f_5p99_720p_video_color;
        panelstruct->videopanel   = &v1_hsd_hx8394f_5p99_720p_video_video_panel;
        panelstruct->commandpanel = &v1_hsd_hx8394f_5p99_720p_video_command_panel;
        panelstruct->state        = &v1_hsd_hx8394f_5p99_720p_video_state;
        panelstruct->laneconfig   = &v1_hsd_hx8394f_5p99_720p_video_lane_config;
        panelstruct->paneltiminginfo    = &v1_hsd_hx8394f_5p99_720p_video_timing_info;
        panelstruct->panelresetseq = &v1_hsd_hx8394f_5p99_720p_video_reset_seq;
        panelstruct->backlightinfo = &v1_hsd_hx8394f_5p99_720p_video_backlight;
        if(V1_HSD_HX8394F_5P99_720P_VIDEO_BIAS_IC_ARRAY == 0)
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = v1_hsd_hx8394f_5p99_720p_video_bias_ic_array;
        }
        panelstruct->lcd_bias_ic_info.num_of_lcd_bias_ic_list = V1_HSD_HX8394F_5P99_720P_VIDEO_BIAS_IC_ARRAY;
        if(V1_HSD_HX8394F_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY == 0)
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = v1_hsd_hx8394f_5p99_720p_video_backlight_ic_array;
        }
        panelstruct->lcd_backlight_ic_info.num_of_lcd_backlight_ic_list = V1_HSD_HX8394F_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY;
        pinfo->labibb = &v1_hsd_hx8394f_5p99_720p_video_labibb;
        pinfo->mipi.panel_on_cmds  = v1_hsd_hx8394f_5p99_720p_video_on_command;
        pinfo->mipi.num_of_panel_on_cmds = ARRAY_SIZE(v1_hsd_hx8394f_5p99_720p_video_on_command);
        pinfo->mipi.panel_off_cmds  = v1_hsd_hx8394f_5p99_720p_video_off_command;
        pinfo->mipi.num_of_panel_off_cmds = ARRAY_SIZE(v1_hsd_hx8394f_5p99_720p_video_off_command);
        memcpy(phy_db->timing, v1_hsd_hx8394f_5p99_720p_video_timings, sizeof(v1_hsd_hx8394f_5p99_720p_video_timings));
        memcpy(panel_regulator_settings, v1_hsd_hx8394f_5p99_720p_video_regulator_setting, sizeof(v1_hsd_hx8394f_5p99_720p_video_regulator_setting));
        pinfo->pipe_type = v1_hsd_hx8394f_5p99_720p_video_mdp_pipe_type;
        phy_db->pll_type = v1_hsd_hx8394f_5p99_720p_video_dsi_pll_type;
        pinfo->mipi.signature = v1_hsd_hx8394f_5p99_720p_video_mipi_signature;
        lcdkit_config.lcd_platform   = &v1_hsd_hx8394f_5p99_720p_video_panel_platform_config;
        lcdkit_config.lcd_misc   = &v1_hsd_hx8394f_5p99_720p_video_panel_misc_info;
        lcdkit_config.lcd_delay     = &v1_hsd_hx8394f_5p99_720p_video_panel_delay_ctrl;
        pinfo->mipi.tx_eot_append = lcdkit_config.lcd_misc->tx_eot_append;
        pinfo->mipi.rx_eot_ignore = lcdkit_config.lcd_misc->rx_eot_ignore;
        phy_db->regulator_mode = lcdkit_config.lcd_misc->mipi_regulator_mode;
        lcdkit_config.backlight_cmds   = v1_hsd_hx8394f_5p99_720p_video_backlight_command;
        lcdkit_config.num_of_backlight_cmds   = ARRAY_SIZE(v1_hsd_hx8394f_5p99_720p_video_backlight_command);
        break;

    case V1_AUO_OTM1911A_7P12_1080P_VIDEO_PANEL:
        panelstruct->paneldata    = &v1_auo_otm1911a_7p12_1080p_video_panel_data;
        panelstruct->panelres     = &v1_auo_otm1911a_7p12_1080p_video_panel_res;
        panelstruct->color        = &v1_auo_otm1911a_7p12_1080p_video_color;
        panelstruct->videopanel   = &v1_auo_otm1911a_7p12_1080p_video_video_panel;
        panelstruct->commandpanel = &v1_auo_otm1911a_7p12_1080p_video_command_panel;
        panelstruct->state        = &v1_auo_otm1911a_7p12_1080p_video_state;
        panelstruct->laneconfig   = &v1_auo_otm1911a_7p12_1080p_video_lane_config;
        panelstruct->paneltiminginfo    = &v1_auo_otm1911a_7p12_1080p_video_timing_info;
        panelstruct->panelresetseq = &v1_auo_otm1911a_7p12_1080p_video_reset_seq;
        panelstruct->backlightinfo = &v1_auo_otm1911a_7p12_1080p_video_backlight;
        if(V1_AUO_OTM1911A_7P12_1080P_VIDEO_BIAS_IC_ARRAY == 0)
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = v1_auo_otm1911a_7p12_1080p_video_bias_ic_array;
        }
        panelstruct->lcd_bias_ic_info.num_of_lcd_bias_ic_list = V1_AUO_OTM1911A_7P12_1080P_VIDEO_BIAS_IC_ARRAY;
        if(V1_AUO_OTM1911A_7P12_1080P_VIDEO_BACKLIGHT_IC_ARRAY == 0)
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = v1_auo_otm1911a_7p12_1080p_video_backlight_ic_array;
        }
        panelstruct->lcd_backlight_ic_info.num_of_lcd_backlight_ic_list = V1_AUO_OTM1911A_7P12_1080P_VIDEO_BACKLIGHT_IC_ARRAY;
        pinfo->labibb = &v1_auo_otm1911a_7p12_1080p_video_labibb;
        pinfo->mipi.panel_on_cmds  = v1_auo_otm1911a_7p12_1080p_video_on_command;
        pinfo->mipi.num_of_panel_on_cmds = ARRAY_SIZE(v1_auo_otm1911a_7p12_1080p_video_on_command);
        pinfo->mipi.panel_off_cmds  = v1_auo_otm1911a_7p12_1080p_video_off_command;
        pinfo->mipi.num_of_panel_off_cmds = ARRAY_SIZE(v1_auo_otm1911a_7p12_1080p_video_off_command);
        memcpy(phy_db->timing, v1_auo_otm1911a_7p12_1080p_video_timings, sizeof(v1_auo_otm1911a_7p12_1080p_video_timings));
        memcpy(panel_regulator_settings, v1_auo_otm1911a_7p12_1080p_video_regulator_setting, sizeof(v1_auo_otm1911a_7p12_1080p_video_regulator_setting));
        pinfo->pipe_type = v1_auo_otm1911a_7p12_1080p_video_mdp_pipe_type;
        phy_db->pll_type = v1_auo_otm1911a_7p12_1080p_video_dsi_pll_type;
        pinfo->mipi.signature = v1_auo_otm1911a_7p12_1080p_video_mipi_signature;
        lcdkit_config.lcd_platform   = &v1_auo_otm1911a_7p12_1080p_video_panel_platform_config;
        lcdkit_config.lcd_misc   = &v1_auo_otm1911a_7p12_1080p_video_panel_misc_info;
        lcdkit_config.lcd_delay     = &v1_auo_otm1911a_7p12_1080p_video_panel_delay_ctrl;
        pinfo->mipi.tx_eot_append = lcdkit_config.lcd_misc->tx_eot_append;
        pinfo->mipi.rx_eot_ignore = lcdkit_config.lcd_misc->rx_eot_ignore;
        phy_db->regulator_mode = lcdkit_config.lcd_misc->mipi_regulator_mode;
        lcdkit_config.backlight_cmds   = v1_auo_otm1911a_7p12_1080p_video_backlight_command;
        lcdkit_config.num_of_backlight_cmds   = ARRAY_SIZE(v1_auo_otm1911a_7p12_1080p_video_backlight_command);
        break;

    case V1_EBBG_HX8399C_7P12_1080P_VIDEO_PANEL:
        panelstruct->paneldata    = &v1_ebbg_hx8399c_7p12_1080p_video_panel_data;
        panelstruct->panelres     = &v1_ebbg_hx8399c_7p12_1080p_video_panel_res;
        panelstruct->color        = &v1_ebbg_hx8399c_7p12_1080p_video_color;
        panelstruct->videopanel   = &v1_ebbg_hx8399c_7p12_1080p_video_video_panel;
        panelstruct->commandpanel = &v1_ebbg_hx8399c_7p12_1080p_video_command_panel;
        panelstruct->state        = &v1_ebbg_hx8399c_7p12_1080p_video_state;
        panelstruct->laneconfig   = &v1_ebbg_hx8399c_7p12_1080p_video_lane_config;
        panelstruct->paneltiminginfo    = &v1_ebbg_hx8399c_7p12_1080p_video_timing_info;
        panelstruct->panelresetseq = &v1_ebbg_hx8399c_7p12_1080p_video_reset_seq;
        panelstruct->backlightinfo = &v1_ebbg_hx8399c_7p12_1080p_video_backlight;
        if(V1_EBBG_HX8399C_7P12_1080P_VIDEO_BIAS_IC_ARRAY == 0)
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = v1_ebbg_hx8399c_7p12_1080p_video_bias_ic_array;
        }
        panelstruct->lcd_bias_ic_info.num_of_lcd_bias_ic_list = V1_EBBG_HX8399C_7P12_1080P_VIDEO_BIAS_IC_ARRAY;
        if(V1_EBBG_HX8399C_7P12_1080P_VIDEO_BACKLIGHT_IC_ARRAY == 0)
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = v1_ebbg_hx8399c_7p12_1080p_video_backlight_ic_array;
        }
        panelstruct->lcd_backlight_ic_info.num_of_lcd_backlight_ic_list = V1_EBBG_HX8399C_7P12_1080P_VIDEO_BACKLIGHT_IC_ARRAY;
        pinfo->labibb = &v1_ebbg_hx8399c_7p12_1080p_video_labibb;
        pinfo->mipi.panel_on_cmds  = v1_ebbg_hx8399c_7p12_1080p_video_on_command;
        pinfo->mipi.num_of_panel_on_cmds = ARRAY_SIZE(v1_ebbg_hx8399c_7p12_1080p_video_on_command);
        pinfo->mipi.panel_off_cmds  = v1_ebbg_hx8399c_7p12_1080p_video_off_command;
        pinfo->mipi.num_of_panel_off_cmds = ARRAY_SIZE(v1_ebbg_hx8399c_7p12_1080p_video_off_command);
        memcpy(phy_db->timing, v1_ebbg_hx8399c_7p12_1080p_video_timings, sizeof(v1_ebbg_hx8399c_7p12_1080p_video_timings));
        memcpy(panel_regulator_settings, v1_ebbg_hx8399c_7p12_1080p_video_regulator_setting, sizeof(v1_ebbg_hx8399c_7p12_1080p_video_regulator_setting));
        pinfo->pipe_type = v1_ebbg_hx8399c_7p12_1080p_video_mdp_pipe_type;
        phy_db->pll_type = v1_ebbg_hx8399c_7p12_1080p_video_dsi_pll_type;
        pinfo->mipi.signature = v1_ebbg_hx8399c_7p12_1080p_video_mipi_signature;
        lcdkit_config.lcd_platform   = &v1_ebbg_hx8399c_7p12_1080p_video_panel_platform_config;
        lcdkit_config.lcd_misc   = &v1_ebbg_hx8399c_7p12_1080p_video_panel_misc_info;
        lcdkit_config.lcd_delay     = &v1_ebbg_hx8399c_7p12_1080p_video_panel_delay_ctrl;
        pinfo->mipi.tx_eot_append = lcdkit_config.lcd_misc->tx_eot_append;
        pinfo->mipi.rx_eot_ignore = lcdkit_config.lcd_misc->rx_eot_ignore;
        phy_db->regulator_mode = lcdkit_config.lcd_misc->mipi_regulator_mode;
        lcdkit_config.backlight_cmds   = v1_ebbg_hx8399c_7p12_1080p_video_backlight_command;
        lcdkit_config.num_of_backlight_cmds   = ARRAY_SIZE(v1_ebbg_hx8399c_7p12_1080p_video_backlight_command);
        break;

    case ARES_AL00_VB_DJN_ILI9881C_5P99_720P_VIDEO_PANEL:
        panelstruct->paneldata    = &ares_al00_vb_djn_ili9881c_5p99_720p_video_panel_data;
        panelstruct->panelres     = &ares_al00_vb_djn_ili9881c_5p99_720p_video_panel_res;
        panelstruct->color        = &ares_al00_vb_djn_ili9881c_5p99_720p_video_color;
        panelstruct->videopanel   = &ares_al00_vb_djn_ili9881c_5p99_720p_video_video_panel;
        panelstruct->commandpanel = &ares_al00_vb_djn_ili9881c_5p99_720p_video_command_panel;
        panelstruct->state        = &ares_al00_vb_djn_ili9881c_5p99_720p_video_state;
        panelstruct->laneconfig   = &ares_al00_vb_djn_ili9881c_5p99_720p_video_lane_config;
        panelstruct->paneltiminginfo    = &ares_al00_vb_djn_ili9881c_5p99_720p_video_timing_info;
        panelstruct->panelresetseq = &ares_al00_vb_djn_ili9881c_5p99_720p_video_reset_seq;
        panelstruct->backlightinfo = &ares_al00_vb_djn_ili9881c_5p99_720p_video_backlight;
        if(ARES_AL00_VB_DJN_ILI9881C_5P99_720P_VIDEO_BIAS_IC_ARRAY == 0)
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = ares_al00_vb_djn_ili9881c_5p99_720p_video_bias_ic_array;
        }
        panelstruct->lcd_bias_ic_info.num_of_lcd_bias_ic_list = ARES_AL00_VB_DJN_ILI9881C_5P99_720P_VIDEO_BIAS_IC_ARRAY;
        if(ARES_AL00_VB_DJN_ILI9881C_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY == 0)
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = ares_al00_vb_djn_ili9881c_5p99_720p_video_backlight_ic_array;
        }
        panelstruct->lcd_backlight_ic_info.num_of_lcd_backlight_ic_list = ARES_AL00_VB_DJN_ILI9881C_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY;
        pinfo->labibb = &ares_al00_vb_djn_ili9881c_5p99_720p_video_labibb;
        pinfo->mipi.panel_on_cmds  = ares_al00_vb_djn_ili9881c_5p99_720p_video_on_command;
        pinfo->mipi.num_of_panel_on_cmds = ARRAY_SIZE(ares_al00_vb_djn_ili9881c_5p99_720p_video_on_command);
        pinfo->mipi.panel_off_cmds  = ares_al00_vb_djn_ili9881c_5p99_720p_video_off_command;
        pinfo->mipi.num_of_panel_off_cmds = ARRAY_SIZE(ares_al00_vb_djn_ili9881c_5p99_720p_video_off_command);
        memcpy(phy_db->timing, ares_al00_vb_djn_ili9881c_5p99_720p_video_timings, sizeof(ares_al00_vb_djn_ili9881c_5p99_720p_video_timings));
        memcpy(panel_regulator_settings, ares_al00_vb_djn_ili9881c_5p99_720p_video_regulator_setting, sizeof(ares_al00_vb_djn_ili9881c_5p99_720p_video_regulator_setting));
        pinfo->pipe_type = ares_al00_vb_djn_ili9881c_5p99_720p_video_mdp_pipe_type;
        phy_db->pll_type = ares_al00_vb_djn_ili9881c_5p99_720p_video_dsi_pll_type;
        pinfo->mipi.signature = ares_al00_vb_djn_ili9881c_5p99_720p_video_mipi_signature;
        lcdkit_config.lcd_platform   = &ares_al00_vb_djn_ili9881c_5p99_720p_video_panel_platform_config;
        lcdkit_config.lcd_misc   = &ares_al00_vb_djn_ili9881c_5p99_720p_video_panel_misc_info;
        lcdkit_config.lcd_delay     = &ares_al00_vb_djn_ili9881c_5p99_720p_video_panel_delay_ctrl;
        pinfo->mipi.tx_eot_append = lcdkit_config.lcd_misc->tx_eot_append;
        pinfo->mipi.rx_eot_ignore = lcdkit_config.lcd_misc->rx_eot_ignore;
        phy_db->regulator_mode = lcdkit_config.lcd_misc->mipi_regulator_mode;
        lcdkit_config.backlight_cmds   = ares_al00_vb_djn_ili9881c_5p99_720p_video_backlight_command;
        lcdkit_config.num_of_backlight_cmds   = ARRAY_SIZE(ares_al00_vb_djn_ili9881c_5p99_720p_video_backlight_command);
        break;

    case ARES_AL00_VC_DJN_ILI9881C_5P99_720P_VIDEO_PANEL:
        panelstruct->paneldata    = &ares_al00_vc_djn_ili9881c_5p99_720p_video_panel_data;
        panelstruct->panelres     = &ares_al00_vc_djn_ili9881c_5p99_720p_video_panel_res;
        panelstruct->color        = &ares_al00_vc_djn_ili9881c_5p99_720p_video_color;
        panelstruct->videopanel   = &ares_al00_vc_djn_ili9881c_5p99_720p_video_video_panel;
        panelstruct->commandpanel = &ares_al00_vc_djn_ili9881c_5p99_720p_video_command_panel;
        panelstruct->state        = &ares_al00_vc_djn_ili9881c_5p99_720p_video_state;
        panelstruct->laneconfig   = &ares_al00_vc_djn_ili9881c_5p99_720p_video_lane_config;
        panelstruct->paneltiminginfo    = &ares_al00_vc_djn_ili9881c_5p99_720p_video_timing_info;
        panelstruct->panelresetseq = &ares_al00_vc_djn_ili9881c_5p99_720p_video_reset_seq;
        panelstruct->backlightinfo = &ares_al00_vc_djn_ili9881c_5p99_720p_video_backlight;
        if(ARES_AL00_VC_DJN_ILI9881C_5P99_720P_VIDEO_BIAS_IC_ARRAY == 0)
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = ares_al00_vc_djn_ili9881c_5p99_720p_video_bias_ic_array;
        }
        panelstruct->lcd_bias_ic_info.num_of_lcd_bias_ic_list = ARES_AL00_VC_DJN_ILI9881C_5P99_720P_VIDEO_BIAS_IC_ARRAY;
        if(ARES_AL00_VC_DJN_ILI9881C_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY == 0)
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = ares_al00_vc_djn_ili9881c_5p99_720p_video_backlight_ic_array;
        }
        panelstruct->lcd_backlight_ic_info.num_of_lcd_backlight_ic_list = ARES_AL00_VC_DJN_ILI9881C_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY;
        pinfo->labibb = &ares_al00_vc_djn_ili9881c_5p99_720p_video_labibb;
        pinfo->mipi.panel_on_cmds  = ares_al00_vc_djn_ili9881c_5p99_720p_video_on_command;
        pinfo->mipi.num_of_panel_on_cmds = ARRAY_SIZE(ares_al00_vc_djn_ili9881c_5p99_720p_video_on_command);
        pinfo->mipi.panel_off_cmds  = ares_al00_vc_djn_ili9881c_5p99_720p_video_off_command;
        pinfo->mipi.num_of_panel_off_cmds = ARRAY_SIZE(ares_al00_vc_djn_ili9881c_5p99_720p_video_off_command);
        memcpy(phy_db->timing, ares_al00_vc_djn_ili9881c_5p99_720p_video_timings, sizeof(ares_al00_vc_djn_ili9881c_5p99_720p_video_timings));
        memcpy(panel_regulator_settings, ares_al00_vc_djn_ili9881c_5p99_720p_video_regulator_setting, sizeof(ares_al00_vc_djn_ili9881c_5p99_720p_video_regulator_setting));
        pinfo->pipe_type = ares_al00_vc_djn_ili9881c_5p99_720p_video_mdp_pipe_type;
        phy_db->pll_type = ares_al00_vc_djn_ili9881c_5p99_720p_video_dsi_pll_type;
        pinfo->mipi.signature = ares_al00_vc_djn_ili9881c_5p99_720p_video_mipi_signature;
        lcdkit_config.lcd_platform   = &ares_al00_vc_djn_ili9881c_5p99_720p_video_panel_platform_config;
        lcdkit_config.lcd_misc   = &ares_al00_vc_djn_ili9881c_5p99_720p_video_panel_misc_info;
        lcdkit_config.lcd_delay     = &ares_al00_vc_djn_ili9881c_5p99_720p_video_panel_delay_ctrl;
        pinfo->mipi.tx_eot_append = lcdkit_config.lcd_misc->tx_eot_append;
        pinfo->mipi.rx_eot_ignore = lcdkit_config.lcd_misc->rx_eot_ignore;
        phy_db->regulator_mode = lcdkit_config.lcd_misc->mipi_regulator_mode;
        lcdkit_config.backlight_cmds   = ares_al00_vc_djn_ili9881c_5p99_720p_video_backlight_command;
        lcdkit_config.num_of_backlight_cmds   = ARRAY_SIZE(ares_al00_vc_djn_ili9881c_5p99_720p_video_backlight_command);
        break;

    case ARES_AL10_VC_DJN_ILI9881C_5P99_720P_VIDEO_PANEL:
        panelstruct->paneldata    = &ares_al10_vc_djn_ili9881c_5p99_720p_video_panel_data;
        panelstruct->panelres     = &ares_al10_vc_djn_ili9881c_5p99_720p_video_panel_res;
        panelstruct->color        = &ares_al10_vc_djn_ili9881c_5p99_720p_video_color;
        panelstruct->videopanel   = &ares_al10_vc_djn_ili9881c_5p99_720p_video_video_panel;
        panelstruct->commandpanel = &ares_al10_vc_djn_ili9881c_5p99_720p_video_command_panel;
        panelstruct->state        = &ares_al10_vc_djn_ili9881c_5p99_720p_video_state;
        panelstruct->laneconfig   = &ares_al10_vc_djn_ili9881c_5p99_720p_video_lane_config;
        panelstruct->paneltiminginfo    = &ares_al10_vc_djn_ili9881c_5p99_720p_video_timing_info;
        panelstruct->panelresetseq = &ares_al10_vc_djn_ili9881c_5p99_720p_video_reset_seq;
        panelstruct->backlightinfo = &ares_al10_vc_djn_ili9881c_5p99_720p_video_backlight;
        if(ARES_AL10_VC_DJN_ILI9881C_5P99_720P_VIDEO_BIAS_IC_ARRAY == 0)
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = ares_al10_vc_djn_ili9881c_5p99_720p_video_bias_ic_array;
        }
        panelstruct->lcd_bias_ic_info.num_of_lcd_bias_ic_list = ARES_AL10_VC_DJN_ILI9881C_5P99_720P_VIDEO_BIAS_IC_ARRAY;
        if(ARES_AL10_VC_DJN_ILI9881C_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY == 0)
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = ares_al10_vc_djn_ili9881c_5p99_720p_video_backlight_ic_array;
        }
        panelstruct->lcd_backlight_ic_info.num_of_lcd_backlight_ic_list = ARES_AL10_VC_DJN_ILI9881C_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY;
        pinfo->labibb = &ares_al10_vc_djn_ili9881c_5p99_720p_video_labibb;
        pinfo->mipi.panel_on_cmds  = ares_al10_vc_djn_ili9881c_5p99_720p_video_on_command;
        pinfo->mipi.num_of_panel_on_cmds = ARRAY_SIZE(ares_al10_vc_djn_ili9881c_5p99_720p_video_on_command);
        pinfo->mipi.panel_off_cmds  = ares_al10_vc_djn_ili9881c_5p99_720p_video_off_command;
        pinfo->mipi.num_of_panel_off_cmds = ARRAY_SIZE(ares_al10_vc_djn_ili9881c_5p99_720p_video_off_command);
        memcpy(phy_db->timing, ares_al10_vc_djn_ili9881c_5p99_720p_video_timings, sizeof(ares_al10_vc_djn_ili9881c_5p99_720p_video_timings));
        memcpy(panel_regulator_settings, ares_al10_vc_djn_ili9881c_5p99_720p_video_regulator_setting, sizeof(ares_al10_vc_djn_ili9881c_5p99_720p_video_regulator_setting));
        pinfo->pipe_type = ares_al10_vc_djn_ili9881c_5p99_720p_video_mdp_pipe_type;
        phy_db->pll_type = ares_al10_vc_djn_ili9881c_5p99_720p_video_dsi_pll_type;
        pinfo->mipi.signature = ares_al10_vc_djn_ili9881c_5p99_720p_video_mipi_signature;
        lcdkit_config.lcd_platform   = &ares_al10_vc_djn_ili9881c_5p99_720p_video_panel_platform_config;
        lcdkit_config.lcd_misc   = &ares_al10_vc_djn_ili9881c_5p99_720p_video_panel_misc_info;
        lcdkit_config.lcd_delay     = &ares_al10_vc_djn_ili9881c_5p99_720p_video_panel_delay_ctrl;
        pinfo->mipi.tx_eot_append = lcdkit_config.lcd_misc->tx_eot_append;
        pinfo->mipi.rx_eot_ignore = lcdkit_config.lcd_misc->rx_eot_ignore;
        phy_db->regulator_mode = lcdkit_config.lcd_misc->mipi_regulator_mode;
        lcdkit_config.backlight_cmds   = ares_al10_vc_djn_ili9881c_5p99_720p_video_backlight_command;
        lcdkit_config.num_of_backlight_cmds   = ARRAY_SIZE(ares_al10_vc_djn_ili9881c_5p99_720p_video_backlight_command);
        break;

    case ARES_L22_VA_DJN_ILI9881C_5P99_720P_VIDEO_PANEL:
        panelstruct->paneldata    = &ares_l22_va_djn_ili9881c_5p99_720p_video_panel_data;
        panelstruct->panelres     = &ares_l22_va_djn_ili9881c_5p99_720p_video_panel_res;
        panelstruct->color        = &ares_l22_va_djn_ili9881c_5p99_720p_video_color;
        panelstruct->videopanel   = &ares_l22_va_djn_ili9881c_5p99_720p_video_video_panel;
        panelstruct->commandpanel = &ares_l22_va_djn_ili9881c_5p99_720p_video_command_panel;
        panelstruct->state        = &ares_l22_va_djn_ili9881c_5p99_720p_video_state;
        panelstruct->laneconfig   = &ares_l22_va_djn_ili9881c_5p99_720p_video_lane_config;
        panelstruct->paneltiminginfo    = &ares_l22_va_djn_ili9881c_5p99_720p_video_timing_info;
        panelstruct->panelresetseq = &ares_l22_va_djn_ili9881c_5p99_720p_video_reset_seq;
        panelstruct->backlightinfo = &ares_l22_va_djn_ili9881c_5p99_720p_video_backlight;
        if(ARES_L22_VA_DJN_ILI9881C_5P99_720P_VIDEO_BIAS_IC_ARRAY == 0)
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = ares_l22_va_djn_ili9881c_5p99_720p_video_bias_ic_array;
        }
        panelstruct->lcd_bias_ic_info.num_of_lcd_bias_ic_list = ARES_L22_VA_DJN_ILI9881C_5P99_720P_VIDEO_BIAS_IC_ARRAY;
        if(ARES_L22_VA_DJN_ILI9881C_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY == 0)
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = ares_l22_va_djn_ili9881c_5p99_720p_video_backlight_ic_array;
        }
        panelstruct->lcd_backlight_ic_info.num_of_lcd_backlight_ic_list = ARES_L22_VA_DJN_ILI9881C_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY;
        pinfo->labibb = &ares_l22_va_djn_ili9881c_5p99_720p_video_labibb;
        pinfo->mipi.panel_on_cmds  = ares_l22_va_djn_ili9881c_5p99_720p_video_on_command;
        pinfo->mipi.num_of_panel_on_cmds = ARRAY_SIZE(ares_l22_va_djn_ili9881c_5p99_720p_video_on_command);
        pinfo->mipi.panel_off_cmds  = ares_l22_va_djn_ili9881c_5p99_720p_video_off_command;
        pinfo->mipi.num_of_panel_off_cmds = ARRAY_SIZE(ares_l22_va_djn_ili9881c_5p99_720p_video_off_command);
        memcpy(phy_db->timing, ares_l22_va_djn_ili9881c_5p99_720p_video_timings, sizeof(ares_l22_va_djn_ili9881c_5p99_720p_video_timings));
        memcpy(panel_regulator_settings, ares_l22_va_djn_ili9881c_5p99_720p_video_regulator_setting, sizeof(ares_l22_va_djn_ili9881c_5p99_720p_video_regulator_setting));
        pinfo->pipe_type = ares_l22_va_djn_ili9881c_5p99_720p_video_mdp_pipe_type;
        phy_db->pll_type = ares_l22_va_djn_ili9881c_5p99_720p_video_dsi_pll_type;
        pinfo->mipi.signature = ares_l22_va_djn_ili9881c_5p99_720p_video_mipi_signature;
        lcdkit_config.lcd_platform   = &ares_l22_va_djn_ili9881c_5p99_720p_video_panel_platform_config;
        lcdkit_config.lcd_misc   = &ares_l22_va_djn_ili9881c_5p99_720p_video_panel_misc_info;
        lcdkit_config.lcd_delay     = &ares_l22_va_djn_ili9881c_5p99_720p_video_panel_delay_ctrl;
        pinfo->mipi.tx_eot_append = lcdkit_config.lcd_misc->tx_eot_append;
        pinfo->mipi.rx_eot_ignore = lcdkit_config.lcd_misc->rx_eot_ignore;
        phy_db->regulator_mode = lcdkit_config.lcd_misc->mipi_regulator_mode;
        lcdkit_config.backlight_cmds   = ares_l22_va_djn_ili9881c_5p99_720p_video_backlight_command;
        lcdkit_config.num_of_backlight_cmds   = ARRAY_SIZE(ares_l22_va_djn_ili9881c_5p99_720p_video_backlight_command);
        break;

    case ARES_AL00_VB_HSD_HX8394F_5P99_720P_VIDEO_PANEL:
        panelstruct->paneldata    = &ares_al00_vb_hsd_hx8394f_5p99_720p_video_panel_data;
        panelstruct->panelres     = &ares_al00_vb_hsd_hx8394f_5p99_720p_video_panel_res;
        panelstruct->color        = &ares_al00_vb_hsd_hx8394f_5p99_720p_video_color;
        panelstruct->videopanel   = &ares_al00_vb_hsd_hx8394f_5p99_720p_video_video_panel;
        panelstruct->commandpanel = &ares_al00_vb_hsd_hx8394f_5p99_720p_video_command_panel;
        panelstruct->state        = &ares_al00_vb_hsd_hx8394f_5p99_720p_video_state;
        panelstruct->laneconfig   = &ares_al00_vb_hsd_hx8394f_5p99_720p_video_lane_config;
        panelstruct->paneltiminginfo    = &ares_al00_vb_hsd_hx8394f_5p99_720p_video_timing_info;
        panelstruct->panelresetseq = &ares_al00_vb_hsd_hx8394f_5p99_720p_video_reset_seq;
        panelstruct->backlightinfo = &ares_al00_vb_hsd_hx8394f_5p99_720p_video_backlight;
        if(ARES_AL00_VB_HSD_HX8394F_5P99_720P_VIDEO_BIAS_IC_ARRAY == 0)
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = ares_al00_vb_hsd_hx8394f_5p99_720p_video_bias_ic_array;
        }
        panelstruct->lcd_bias_ic_info.num_of_lcd_bias_ic_list = ARES_AL00_VB_HSD_HX8394F_5P99_720P_VIDEO_BIAS_IC_ARRAY;
        if(ARES_AL00_VB_HSD_HX8394F_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY == 0)
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = ares_al00_vb_hsd_hx8394f_5p99_720p_video_backlight_ic_array;
        }
        panelstruct->lcd_backlight_ic_info.num_of_lcd_backlight_ic_list = ARES_AL00_VB_HSD_HX8394F_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY;
        pinfo->labibb = &ares_al00_vb_hsd_hx8394f_5p99_720p_video_labibb;
        pinfo->mipi.panel_on_cmds  = ares_al00_vb_hsd_hx8394f_5p99_720p_video_on_command;
        pinfo->mipi.num_of_panel_on_cmds = ARRAY_SIZE(ares_al00_vb_hsd_hx8394f_5p99_720p_video_on_command);
        pinfo->mipi.panel_off_cmds  = ares_al00_vb_hsd_hx8394f_5p99_720p_video_off_command;
        pinfo->mipi.num_of_panel_off_cmds = ARRAY_SIZE(ares_al00_vb_hsd_hx8394f_5p99_720p_video_off_command);
        memcpy(phy_db->timing, ares_al00_vb_hsd_hx8394f_5p99_720p_video_timings, sizeof(ares_al00_vb_hsd_hx8394f_5p99_720p_video_timings));
        memcpy(panel_regulator_settings, ares_al00_vb_hsd_hx8394f_5p99_720p_video_regulator_setting, sizeof(ares_al00_vb_hsd_hx8394f_5p99_720p_video_regulator_setting));
        pinfo->pipe_type = ares_al00_vb_hsd_hx8394f_5p99_720p_video_mdp_pipe_type;
        phy_db->pll_type = ares_al00_vb_hsd_hx8394f_5p99_720p_video_dsi_pll_type;
        pinfo->mipi.signature = ares_al00_vb_hsd_hx8394f_5p99_720p_video_mipi_signature;
        lcdkit_config.lcd_platform   = &ares_al00_vb_hsd_hx8394f_5p99_720p_video_panel_platform_config;
        lcdkit_config.lcd_misc   = &ares_al00_vb_hsd_hx8394f_5p99_720p_video_panel_misc_info;
        lcdkit_config.lcd_delay     = &ares_al00_vb_hsd_hx8394f_5p99_720p_video_panel_delay_ctrl;
        pinfo->mipi.tx_eot_append = lcdkit_config.lcd_misc->tx_eot_append;
        pinfo->mipi.rx_eot_ignore = lcdkit_config.lcd_misc->rx_eot_ignore;
        phy_db->regulator_mode = lcdkit_config.lcd_misc->mipi_regulator_mode;
        lcdkit_config.backlight_cmds   = ares_al00_vb_hsd_hx8394f_5p99_720p_video_backlight_command;
        lcdkit_config.num_of_backlight_cmds   = ARRAY_SIZE(ares_al00_vb_hsd_hx8394f_5p99_720p_video_backlight_command);
        break;

    case ARES_AL00_VC_HSD_HX8394F_5P99_720P_VIDEO_PANEL:
        panelstruct->paneldata    = &ares_al00_vc_hsd_hx8394f_5p99_720p_video_panel_data;
        panelstruct->panelres     = &ares_al00_vc_hsd_hx8394f_5p99_720p_video_panel_res;
        panelstruct->color        = &ares_al00_vc_hsd_hx8394f_5p99_720p_video_color;
        panelstruct->videopanel   = &ares_al00_vc_hsd_hx8394f_5p99_720p_video_video_panel;
        panelstruct->commandpanel = &ares_al00_vc_hsd_hx8394f_5p99_720p_video_command_panel;
        panelstruct->state        = &ares_al00_vc_hsd_hx8394f_5p99_720p_video_state;
        panelstruct->laneconfig   = &ares_al00_vc_hsd_hx8394f_5p99_720p_video_lane_config;
        panelstruct->paneltiminginfo    = &ares_al00_vc_hsd_hx8394f_5p99_720p_video_timing_info;
        panelstruct->panelresetseq = &ares_al00_vc_hsd_hx8394f_5p99_720p_video_reset_seq;
        panelstruct->backlightinfo = &ares_al00_vc_hsd_hx8394f_5p99_720p_video_backlight;
        if(ARES_AL00_VC_HSD_HX8394F_5P99_720P_VIDEO_BIAS_IC_ARRAY == 0)
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = ares_al00_vc_hsd_hx8394f_5p99_720p_video_bias_ic_array;
        }
        panelstruct->lcd_bias_ic_info.num_of_lcd_bias_ic_list = ARES_AL00_VC_HSD_HX8394F_5P99_720P_VIDEO_BIAS_IC_ARRAY;
        if(ARES_AL00_VC_HSD_HX8394F_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY == 0)
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = ares_al00_vc_hsd_hx8394f_5p99_720p_video_backlight_ic_array;
        }
        panelstruct->lcd_backlight_ic_info.num_of_lcd_backlight_ic_list = ARES_AL00_VC_HSD_HX8394F_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY;
        pinfo->labibb = &ares_al00_vc_hsd_hx8394f_5p99_720p_video_labibb;
        pinfo->mipi.panel_on_cmds  = ares_al00_vc_hsd_hx8394f_5p99_720p_video_on_command;
        pinfo->mipi.num_of_panel_on_cmds = ARRAY_SIZE(ares_al00_vc_hsd_hx8394f_5p99_720p_video_on_command);
        pinfo->mipi.panel_off_cmds  = ares_al00_vc_hsd_hx8394f_5p99_720p_video_off_command;
        pinfo->mipi.num_of_panel_off_cmds = ARRAY_SIZE(ares_al00_vc_hsd_hx8394f_5p99_720p_video_off_command);
        memcpy(phy_db->timing, ares_al00_vc_hsd_hx8394f_5p99_720p_video_timings, sizeof(ares_al00_vc_hsd_hx8394f_5p99_720p_video_timings));
        memcpy(panel_regulator_settings, ares_al00_vc_hsd_hx8394f_5p99_720p_video_regulator_setting, sizeof(ares_al00_vc_hsd_hx8394f_5p99_720p_video_regulator_setting));
        pinfo->pipe_type = ares_al00_vc_hsd_hx8394f_5p99_720p_video_mdp_pipe_type;
        phy_db->pll_type = ares_al00_vc_hsd_hx8394f_5p99_720p_video_dsi_pll_type;
        pinfo->mipi.signature = ares_al00_vc_hsd_hx8394f_5p99_720p_video_mipi_signature;
        lcdkit_config.lcd_platform   = &ares_al00_vc_hsd_hx8394f_5p99_720p_video_panel_platform_config;
        lcdkit_config.lcd_misc   = &ares_al00_vc_hsd_hx8394f_5p99_720p_video_panel_misc_info;
        lcdkit_config.lcd_delay     = &ares_al00_vc_hsd_hx8394f_5p99_720p_video_panel_delay_ctrl;
        pinfo->mipi.tx_eot_append = lcdkit_config.lcd_misc->tx_eot_append;
        pinfo->mipi.rx_eot_ignore = lcdkit_config.lcd_misc->rx_eot_ignore;
        phy_db->regulator_mode = lcdkit_config.lcd_misc->mipi_regulator_mode;
        lcdkit_config.backlight_cmds   = ares_al00_vc_hsd_hx8394f_5p99_720p_video_backlight_command;
        lcdkit_config.num_of_backlight_cmds   = ARRAY_SIZE(ares_al00_vc_hsd_hx8394f_5p99_720p_video_backlight_command);
        break;

    case ARES_AL10_VC_HSD_HX8394F_5P99_720P_VIDEO_PANEL:
        panelstruct->paneldata    = &ares_al10_vc_hsd_hx8394f_5p99_720p_video_panel_data;
        panelstruct->panelres     = &ares_al10_vc_hsd_hx8394f_5p99_720p_video_panel_res;
        panelstruct->color        = &ares_al10_vc_hsd_hx8394f_5p99_720p_video_color;
        panelstruct->videopanel   = &ares_al10_vc_hsd_hx8394f_5p99_720p_video_video_panel;
        panelstruct->commandpanel = &ares_al10_vc_hsd_hx8394f_5p99_720p_video_command_panel;
        panelstruct->state        = &ares_al10_vc_hsd_hx8394f_5p99_720p_video_state;
        panelstruct->laneconfig   = &ares_al10_vc_hsd_hx8394f_5p99_720p_video_lane_config;
        panelstruct->paneltiminginfo    = &ares_al10_vc_hsd_hx8394f_5p99_720p_video_timing_info;
        panelstruct->panelresetseq = &ares_al10_vc_hsd_hx8394f_5p99_720p_video_reset_seq;
        panelstruct->backlightinfo = &ares_al10_vc_hsd_hx8394f_5p99_720p_video_backlight;
        if(ARES_AL10_VC_HSD_HX8394F_5P99_720P_VIDEO_BIAS_IC_ARRAY == 0)
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = ares_al10_vc_hsd_hx8394f_5p99_720p_video_bias_ic_array;
        }
        panelstruct->lcd_bias_ic_info.num_of_lcd_bias_ic_list = ARES_AL10_VC_HSD_HX8394F_5P99_720P_VIDEO_BIAS_IC_ARRAY;
        if(ARES_AL10_VC_HSD_HX8394F_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY == 0)
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = ares_al10_vc_hsd_hx8394f_5p99_720p_video_backlight_ic_array;
        }
        panelstruct->lcd_backlight_ic_info.num_of_lcd_backlight_ic_list = ARES_AL10_VC_HSD_HX8394F_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY;
        pinfo->labibb = &ares_al10_vc_hsd_hx8394f_5p99_720p_video_labibb;
        pinfo->mipi.panel_on_cmds  = ares_al10_vc_hsd_hx8394f_5p99_720p_video_on_command;
        pinfo->mipi.num_of_panel_on_cmds = ARRAY_SIZE(ares_al10_vc_hsd_hx8394f_5p99_720p_video_on_command);
        pinfo->mipi.panel_off_cmds  = ares_al10_vc_hsd_hx8394f_5p99_720p_video_off_command;
        pinfo->mipi.num_of_panel_off_cmds = ARRAY_SIZE(ares_al10_vc_hsd_hx8394f_5p99_720p_video_off_command);
        memcpy(phy_db->timing, ares_al10_vc_hsd_hx8394f_5p99_720p_video_timings, sizeof(ares_al10_vc_hsd_hx8394f_5p99_720p_video_timings));
        memcpy(panel_regulator_settings, ares_al10_vc_hsd_hx8394f_5p99_720p_video_regulator_setting, sizeof(ares_al10_vc_hsd_hx8394f_5p99_720p_video_regulator_setting));
        pinfo->pipe_type = ares_al10_vc_hsd_hx8394f_5p99_720p_video_mdp_pipe_type;
        phy_db->pll_type = ares_al10_vc_hsd_hx8394f_5p99_720p_video_dsi_pll_type;
        pinfo->mipi.signature = ares_al10_vc_hsd_hx8394f_5p99_720p_video_mipi_signature;
        lcdkit_config.lcd_platform   = &ares_al10_vc_hsd_hx8394f_5p99_720p_video_panel_platform_config;
        lcdkit_config.lcd_misc   = &ares_al10_vc_hsd_hx8394f_5p99_720p_video_panel_misc_info;
        lcdkit_config.lcd_delay     = &ares_al10_vc_hsd_hx8394f_5p99_720p_video_panel_delay_ctrl;
        pinfo->mipi.tx_eot_append = lcdkit_config.lcd_misc->tx_eot_append;
        pinfo->mipi.rx_eot_ignore = lcdkit_config.lcd_misc->rx_eot_ignore;
        phy_db->regulator_mode = lcdkit_config.lcd_misc->mipi_regulator_mode;
        lcdkit_config.backlight_cmds   = ares_al10_vc_hsd_hx8394f_5p99_720p_video_backlight_command;
        lcdkit_config.num_of_backlight_cmds   = ARRAY_SIZE(ares_al10_vc_hsd_hx8394f_5p99_720p_video_backlight_command);
        break;

    case ARES_L22_VA_HSD_HX8394F_5P99_720P_VIDEO_PANEL:
        panelstruct->paneldata    = &ares_l22_va_hsd_hx8394f_5p99_720p_video_panel_data;
        panelstruct->panelres     = &ares_l22_va_hsd_hx8394f_5p99_720p_video_panel_res;
        panelstruct->color        = &ares_l22_va_hsd_hx8394f_5p99_720p_video_color;
        panelstruct->videopanel   = &ares_l22_va_hsd_hx8394f_5p99_720p_video_video_panel;
        panelstruct->commandpanel = &ares_l22_va_hsd_hx8394f_5p99_720p_video_command_panel;
        panelstruct->state        = &ares_l22_va_hsd_hx8394f_5p99_720p_video_state;
        panelstruct->laneconfig   = &ares_l22_va_hsd_hx8394f_5p99_720p_video_lane_config;
        panelstruct->paneltiminginfo    = &ares_l22_va_hsd_hx8394f_5p99_720p_video_timing_info;
        panelstruct->panelresetseq = &ares_l22_va_hsd_hx8394f_5p99_720p_video_reset_seq;
        panelstruct->backlightinfo = &ares_l22_va_hsd_hx8394f_5p99_720p_video_backlight;
        if(ARES_L22_VA_HSD_HX8394F_5P99_720P_VIDEO_BIAS_IC_ARRAY == 0)
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = ares_l22_va_hsd_hx8394f_5p99_720p_video_bias_ic_array;
        }
        panelstruct->lcd_bias_ic_info.num_of_lcd_bias_ic_list = ARES_L22_VA_HSD_HX8394F_5P99_720P_VIDEO_BIAS_IC_ARRAY;
        if(ARES_L22_VA_HSD_HX8394F_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY == 0)
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = ares_l22_va_hsd_hx8394f_5p99_720p_video_backlight_ic_array;
        }
        panelstruct->lcd_backlight_ic_info.num_of_lcd_backlight_ic_list = ARES_L22_VA_HSD_HX8394F_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY;
        pinfo->labibb = &ares_l22_va_hsd_hx8394f_5p99_720p_video_labibb;
        pinfo->mipi.panel_on_cmds  = ares_l22_va_hsd_hx8394f_5p99_720p_video_on_command;
        pinfo->mipi.num_of_panel_on_cmds = ARRAY_SIZE(ares_l22_va_hsd_hx8394f_5p99_720p_video_on_command);
        pinfo->mipi.panel_off_cmds  = ares_l22_va_hsd_hx8394f_5p99_720p_video_off_command;
        pinfo->mipi.num_of_panel_off_cmds = ARRAY_SIZE(ares_l22_va_hsd_hx8394f_5p99_720p_video_off_command);
        memcpy(phy_db->timing, ares_l22_va_hsd_hx8394f_5p99_720p_video_timings, sizeof(ares_l22_va_hsd_hx8394f_5p99_720p_video_timings));
        memcpy(panel_regulator_settings, ares_l22_va_hsd_hx8394f_5p99_720p_video_regulator_setting, sizeof(ares_l22_va_hsd_hx8394f_5p99_720p_video_regulator_setting));
        pinfo->pipe_type = ares_l22_va_hsd_hx8394f_5p99_720p_video_mdp_pipe_type;
        phy_db->pll_type = ares_l22_va_hsd_hx8394f_5p99_720p_video_dsi_pll_type;
        pinfo->mipi.signature = ares_l22_va_hsd_hx8394f_5p99_720p_video_mipi_signature;
        lcdkit_config.lcd_platform   = &ares_l22_va_hsd_hx8394f_5p99_720p_video_panel_platform_config;
        lcdkit_config.lcd_misc   = &ares_l22_va_hsd_hx8394f_5p99_720p_video_panel_misc_info;
        lcdkit_config.lcd_delay     = &ares_l22_va_hsd_hx8394f_5p99_720p_video_panel_delay_ctrl;
        pinfo->mipi.tx_eot_append = lcdkit_config.lcd_misc->tx_eot_append;
        pinfo->mipi.rx_eot_ignore = lcdkit_config.lcd_misc->rx_eot_ignore;
        phy_db->regulator_mode = lcdkit_config.lcd_misc->mipi_regulator_mode;
        lcdkit_config.backlight_cmds   = ares_l22_va_hsd_hx8394f_5p99_720p_video_backlight_command;
        lcdkit_config.num_of_backlight_cmds   = ARRAY_SIZE(ares_l22_va_hsd_hx8394f_5p99_720p_video_backlight_command);
        break;

    case V1_INX_ILI9881C_5P99_720P_VIDEO_PANEL:
        panelstruct->paneldata    = &v1_inx_ili9881c_5p99_720p_video_panel_data;
        panelstruct->panelres     = &v1_inx_ili9881c_5p99_720p_video_panel_res;
        panelstruct->color        = &v1_inx_ili9881c_5p99_720p_video_color;
        panelstruct->videopanel   = &v1_inx_ili9881c_5p99_720p_video_video_panel;
        panelstruct->commandpanel = &v1_inx_ili9881c_5p99_720p_video_command_panel;
        panelstruct->state        = &v1_inx_ili9881c_5p99_720p_video_state;
        panelstruct->laneconfig   = &v1_inx_ili9881c_5p99_720p_video_lane_config;
        panelstruct->paneltiminginfo    = &v1_inx_ili9881c_5p99_720p_video_timing_info;
        panelstruct->panelresetseq = &v1_inx_ili9881c_5p99_720p_video_reset_seq;
        panelstruct->backlightinfo = &v1_inx_ili9881c_5p99_720p_video_backlight;
        if(V1_INX_ILI9881C_5P99_720P_VIDEO_BIAS_IC_ARRAY == 0)
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = v1_inx_ili9881c_5p99_720p_video_bias_ic_array;
        }
        panelstruct->lcd_bias_ic_info.num_of_lcd_bias_ic_list = V1_INX_ILI9881C_5P99_720P_VIDEO_BIAS_IC_ARRAY;
        if(V1_INX_ILI9881C_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY == 0)
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = v1_inx_ili9881c_5p99_720p_video_backlight_ic_array;
        }
        panelstruct->lcd_backlight_ic_info.num_of_lcd_backlight_ic_list = V1_INX_ILI9881C_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY;
        pinfo->labibb = &v1_inx_ili9881c_5p99_720p_video_labibb;
        pinfo->mipi.panel_on_cmds  = v1_inx_ili9881c_5p99_720p_video_on_command;
        pinfo->mipi.num_of_panel_on_cmds = ARRAY_SIZE(v1_inx_ili9881c_5p99_720p_video_on_command);
        pinfo->mipi.panel_off_cmds  = v1_inx_ili9881c_5p99_720p_video_off_command;
        pinfo->mipi.num_of_panel_off_cmds = ARRAY_SIZE(v1_inx_ili9881c_5p99_720p_video_off_command);
        memcpy(phy_db->timing, v1_inx_ili9881c_5p99_720p_video_timings, sizeof(v1_inx_ili9881c_5p99_720p_video_timings));
        memcpy(panel_regulator_settings, v1_inx_ili9881c_5p99_720p_video_regulator_setting, sizeof(v1_inx_ili9881c_5p99_720p_video_regulator_setting));
        pinfo->pipe_type = v1_inx_ili9881c_5p99_720p_video_mdp_pipe_type;
        phy_db->pll_type = v1_inx_ili9881c_5p99_720p_video_dsi_pll_type;
        pinfo->mipi.signature = v1_inx_ili9881c_5p99_720p_video_mipi_signature;
        lcdkit_config.lcd_platform   = &v1_inx_ili9881c_5p99_720p_video_panel_platform_config;
        lcdkit_config.lcd_misc   = &v1_inx_ili9881c_5p99_720p_video_panel_misc_info;
        lcdkit_config.lcd_delay     = &v1_inx_ili9881c_5p99_720p_video_panel_delay_ctrl;
        pinfo->mipi.tx_eot_append = lcdkit_config.lcd_misc->tx_eot_append;
        pinfo->mipi.rx_eot_ignore = lcdkit_config.lcd_misc->rx_eot_ignore;
        phy_db->regulator_mode = lcdkit_config.lcd_misc->mipi_regulator_mode;
        lcdkit_config.backlight_cmds   = v1_inx_ili9881c_5p99_720p_video_backlight_command;
        lcdkit_config.num_of_backlight_cmds   = ARRAY_SIZE(v1_inx_ili9881c_5p99_720p_video_backlight_command);
        break;

    case ARES_AL00_VB_INX_ILI9881C_5P99_720P_VIDEO_PANEL:
        panelstruct->paneldata    = &ares_al00_vb_inx_ili9881c_5p99_720p_video_panel_data;
        panelstruct->panelres     = &ares_al00_vb_inx_ili9881c_5p99_720p_video_panel_res;
        panelstruct->color        = &ares_al00_vb_inx_ili9881c_5p99_720p_video_color;
        panelstruct->videopanel   = &ares_al00_vb_inx_ili9881c_5p99_720p_video_video_panel;
        panelstruct->commandpanel = &ares_al00_vb_inx_ili9881c_5p99_720p_video_command_panel;
        panelstruct->state        = &ares_al00_vb_inx_ili9881c_5p99_720p_video_state;
        panelstruct->laneconfig   = &ares_al00_vb_inx_ili9881c_5p99_720p_video_lane_config;
        panelstruct->paneltiminginfo    = &ares_al00_vb_inx_ili9881c_5p99_720p_video_timing_info;
        panelstruct->panelresetseq = &ares_al00_vb_inx_ili9881c_5p99_720p_video_reset_seq;
        panelstruct->backlightinfo = &ares_al00_vb_inx_ili9881c_5p99_720p_video_backlight;
        if(ARES_AL00_VB_INX_ILI9881C_5P99_720P_VIDEO_BIAS_IC_ARRAY == 0)
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = ares_al00_vb_inx_ili9881c_5p99_720p_video_bias_ic_array;
        }
        panelstruct->lcd_bias_ic_info.num_of_lcd_bias_ic_list = ARES_AL00_VB_INX_ILI9881C_5P99_720P_VIDEO_BIAS_IC_ARRAY;
        if(ARES_AL00_VB_INX_ILI9881C_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY == 0)
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = ares_al00_vb_inx_ili9881c_5p99_720p_video_backlight_ic_array;
        }
        panelstruct->lcd_backlight_ic_info.num_of_lcd_backlight_ic_list = ARES_AL00_VB_INX_ILI9881C_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY;
        pinfo->labibb = &ares_al00_vb_inx_ili9881c_5p99_720p_video_labibb;
        pinfo->mipi.panel_on_cmds  = ares_al00_vb_inx_ili9881c_5p99_720p_video_on_command;
        pinfo->mipi.num_of_panel_on_cmds = ARRAY_SIZE(ares_al00_vb_inx_ili9881c_5p99_720p_video_on_command);
        pinfo->mipi.panel_off_cmds  = ares_al00_vb_inx_ili9881c_5p99_720p_video_off_command;
        pinfo->mipi.num_of_panel_off_cmds = ARRAY_SIZE(ares_al00_vb_inx_ili9881c_5p99_720p_video_off_command);
        memcpy(phy_db->timing, ares_al00_vb_inx_ili9881c_5p99_720p_video_timings, sizeof(ares_al00_vb_inx_ili9881c_5p99_720p_video_timings));
        memcpy(panel_regulator_settings, ares_al00_vb_inx_ili9881c_5p99_720p_video_regulator_setting, sizeof(ares_al00_vb_inx_ili9881c_5p99_720p_video_regulator_setting));
        pinfo->pipe_type = ares_al00_vb_inx_ili9881c_5p99_720p_video_mdp_pipe_type;
        phy_db->pll_type = ares_al00_vb_inx_ili9881c_5p99_720p_video_dsi_pll_type;
        pinfo->mipi.signature = ares_al00_vb_inx_ili9881c_5p99_720p_video_mipi_signature;
        lcdkit_config.lcd_platform   = &ares_al00_vb_inx_ili9881c_5p99_720p_video_panel_platform_config;
        lcdkit_config.lcd_misc   = &ares_al00_vb_inx_ili9881c_5p99_720p_video_panel_misc_info;
        lcdkit_config.lcd_delay     = &ares_al00_vb_inx_ili9881c_5p99_720p_video_panel_delay_ctrl;
        pinfo->mipi.tx_eot_append = lcdkit_config.lcd_misc->tx_eot_append;
        pinfo->mipi.rx_eot_ignore = lcdkit_config.lcd_misc->rx_eot_ignore;
        phy_db->regulator_mode = lcdkit_config.lcd_misc->mipi_regulator_mode;
        lcdkit_config.backlight_cmds   = ares_al00_vb_inx_ili9881c_5p99_720p_video_backlight_command;
        lcdkit_config.num_of_backlight_cmds   = ARRAY_SIZE(ares_al00_vb_inx_ili9881c_5p99_720p_video_backlight_command);
        break;

    case ARES_AL00_VC_INX_ILI9881C_5P99_720P_VIDEO_PANEL:
        panelstruct->paneldata    = &ares_al00_vc_inx_ili9881c_5p99_720p_video_panel_data;
        panelstruct->panelres     = &ares_al00_vc_inx_ili9881c_5p99_720p_video_panel_res;
        panelstruct->color        = &ares_al00_vc_inx_ili9881c_5p99_720p_video_color;
        panelstruct->videopanel   = &ares_al00_vc_inx_ili9881c_5p99_720p_video_video_panel;
        panelstruct->commandpanel = &ares_al00_vc_inx_ili9881c_5p99_720p_video_command_panel;
        panelstruct->state        = &ares_al00_vc_inx_ili9881c_5p99_720p_video_state;
        panelstruct->laneconfig   = &ares_al00_vc_inx_ili9881c_5p99_720p_video_lane_config;
        panelstruct->paneltiminginfo    = &ares_al00_vc_inx_ili9881c_5p99_720p_video_timing_info;
        panelstruct->panelresetseq = &ares_al00_vc_inx_ili9881c_5p99_720p_video_reset_seq;
        panelstruct->backlightinfo = &ares_al00_vc_inx_ili9881c_5p99_720p_video_backlight;
        if(ARES_AL00_VC_INX_ILI9881C_5P99_720P_VIDEO_BIAS_IC_ARRAY == 0)
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = ares_al00_vc_inx_ili9881c_5p99_720p_video_bias_ic_array;
        }
        panelstruct->lcd_bias_ic_info.num_of_lcd_bias_ic_list = ARES_AL00_VC_INX_ILI9881C_5P99_720P_VIDEO_BIAS_IC_ARRAY;
        if(ARES_AL00_VC_INX_ILI9881C_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY == 0)
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = ares_al00_vc_inx_ili9881c_5p99_720p_video_backlight_ic_array;
        }
        panelstruct->lcd_backlight_ic_info.num_of_lcd_backlight_ic_list = ARES_AL00_VC_INX_ILI9881C_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY;
        pinfo->labibb = &ares_al00_vc_inx_ili9881c_5p99_720p_video_labibb;
        pinfo->mipi.panel_on_cmds  = ares_al00_vc_inx_ili9881c_5p99_720p_video_on_command;
        pinfo->mipi.num_of_panel_on_cmds = ARRAY_SIZE(ares_al00_vc_inx_ili9881c_5p99_720p_video_on_command);
        pinfo->mipi.panel_off_cmds  = ares_al00_vc_inx_ili9881c_5p99_720p_video_off_command;
        pinfo->mipi.num_of_panel_off_cmds = ARRAY_SIZE(ares_al00_vc_inx_ili9881c_5p99_720p_video_off_command);
        memcpy(phy_db->timing, ares_al00_vc_inx_ili9881c_5p99_720p_video_timings, sizeof(ares_al00_vc_inx_ili9881c_5p99_720p_video_timings));
        memcpy(panel_regulator_settings, ares_al00_vc_inx_ili9881c_5p99_720p_video_regulator_setting, sizeof(ares_al00_vc_inx_ili9881c_5p99_720p_video_regulator_setting));
        pinfo->pipe_type = ares_al00_vc_inx_ili9881c_5p99_720p_video_mdp_pipe_type;
        phy_db->pll_type = ares_al00_vc_inx_ili9881c_5p99_720p_video_dsi_pll_type;
        pinfo->mipi.signature = ares_al00_vc_inx_ili9881c_5p99_720p_video_mipi_signature;
        lcdkit_config.lcd_platform   = &ares_al00_vc_inx_ili9881c_5p99_720p_video_panel_platform_config;
        lcdkit_config.lcd_misc   = &ares_al00_vc_inx_ili9881c_5p99_720p_video_panel_misc_info;
        lcdkit_config.lcd_delay     = &ares_al00_vc_inx_ili9881c_5p99_720p_video_panel_delay_ctrl;
        pinfo->mipi.tx_eot_append = lcdkit_config.lcd_misc->tx_eot_append;
        pinfo->mipi.rx_eot_ignore = lcdkit_config.lcd_misc->rx_eot_ignore;
        phy_db->regulator_mode = lcdkit_config.lcd_misc->mipi_regulator_mode;
        lcdkit_config.backlight_cmds   = ares_al00_vc_inx_ili9881c_5p99_720p_video_backlight_command;
        lcdkit_config.num_of_backlight_cmds   = ARRAY_SIZE(ares_al00_vc_inx_ili9881c_5p99_720p_video_backlight_command);
        break;

    case ARES_AL10_VC_INX_ILI9881C_5P99_720P_VIDEO_PANEL:
        panelstruct->paneldata    = &ares_al10_vc_inx_ili9881c_5p99_720p_video_panel_data;
        panelstruct->panelres     = &ares_al10_vc_inx_ili9881c_5p99_720p_video_panel_res;
        panelstruct->color        = &ares_al10_vc_inx_ili9881c_5p99_720p_video_color;
        panelstruct->videopanel   = &ares_al10_vc_inx_ili9881c_5p99_720p_video_video_panel;
        panelstruct->commandpanel = &ares_al10_vc_inx_ili9881c_5p99_720p_video_command_panel;
        panelstruct->state        = &ares_al10_vc_inx_ili9881c_5p99_720p_video_state;
        panelstruct->laneconfig   = &ares_al10_vc_inx_ili9881c_5p99_720p_video_lane_config;
        panelstruct->paneltiminginfo    = &ares_al10_vc_inx_ili9881c_5p99_720p_video_timing_info;
        panelstruct->panelresetseq = &ares_al10_vc_inx_ili9881c_5p99_720p_video_reset_seq;
        panelstruct->backlightinfo = &ares_al10_vc_inx_ili9881c_5p99_720p_video_backlight;
        if(ARES_AL10_VC_INX_ILI9881C_5P99_720P_VIDEO_BIAS_IC_ARRAY == 0)
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = ares_al10_vc_inx_ili9881c_5p99_720p_video_bias_ic_array;
        }
        panelstruct->lcd_bias_ic_info.num_of_lcd_bias_ic_list = ARES_AL10_VC_INX_ILI9881C_5P99_720P_VIDEO_BIAS_IC_ARRAY;
        if(ARES_AL10_VC_INX_ILI9881C_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY == 0)
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = ares_al10_vc_inx_ili9881c_5p99_720p_video_backlight_ic_array;
        }
        panelstruct->lcd_backlight_ic_info.num_of_lcd_backlight_ic_list = ARES_AL10_VC_INX_ILI9881C_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY;
        pinfo->labibb = &ares_al10_vc_inx_ili9881c_5p99_720p_video_labibb;
        pinfo->mipi.panel_on_cmds  = ares_al10_vc_inx_ili9881c_5p99_720p_video_on_command;
        pinfo->mipi.num_of_panel_on_cmds = ARRAY_SIZE(ares_al10_vc_inx_ili9881c_5p99_720p_video_on_command);
        pinfo->mipi.panel_off_cmds  = ares_al10_vc_inx_ili9881c_5p99_720p_video_off_command;
        pinfo->mipi.num_of_panel_off_cmds = ARRAY_SIZE(ares_al10_vc_inx_ili9881c_5p99_720p_video_off_command);
        memcpy(phy_db->timing, ares_al10_vc_inx_ili9881c_5p99_720p_video_timings, sizeof(ares_al10_vc_inx_ili9881c_5p99_720p_video_timings));
        memcpy(panel_regulator_settings, ares_al10_vc_inx_ili9881c_5p99_720p_video_regulator_setting, sizeof(ares_al10_vc_inx_ili9881c_5p99_720p_video_regulator_setting));
        pinfo->pipe_type = ares_al10_vc_inx_ili9881c_5p99_720p_video_mdp_pipe_type;
        phy_db->pll_type = ares_al10_vc_inx_ili9881c_5p99_720p_video_dsi_pll_type;
        pinfo->mipi.signature = ares_al10_vc_inx_ili9881c_5p99_720p_video_mipi_signature;
        lcdkit_config.lcd_platform   = &ares_al10_vc_inx_ili9881c_5p99_720p_video_panel_platform_config;
        lcdkit_config.lcd_misc   = &ares_al10_vc_inx_ili9881c_5p99_720p_video_panel_misc_info;
        lcdkit_config.lcd_delay     = &ares_al10_vc_inx_ili9881c_5p99_720p_video_panel_delay_ctrl;
        pinfo->mipi.tx_eot_append = lcdkit_config.lcd_misc->tx_eot_append;
        pinfo->mipi.rx_eot_ignore = lcdkit_config.lcd_misc->rx_eot_ignore;
        phy_db->regulator_mode = lcdkit_config.lcd_misc->mipi_regulator_mode;
        lcdkit_config.backlight_cmds   = ares_al10_vc_inx_ili9881c_5p99_720p_video_backlight_command;
        lcdkit_config.num_of_backlight_cmds   = ARRAY_SIZE(ares_al10_vc_inx_ili9881c_5p99_720p_video_backlight_command);
        break;

    case ARES_L22_VA_INX_ILI9881C_5P99_720P_VIDEO_PANEL:
        panelstruct->paneldata    = &ares_l22_va_inx_ili9881c_5p99_720p_video_panel_data;
        panelstruct->panelres     = &ares_l22_va_inx_ili9881c_5p99_720p_video_panel_res;
        panelstruct->color        = &ares_l22_va_inx_ili9881c_5p99_720p_video_color;
        panelstruct->videopanel   = &ares_l22_va_inx_ili9881c_5p99_720p_video_video_panel;
        panelstruct->commandpanel = &ares_l22_va_inx_ili9881c_5p99_720p_video_command_panel;
        panelstruct->state        = &ares_l22_va_inx_ili9881c_5p99_720p_video_state;
        panelstruct->laneconfig   = &ares_l22_va_inx_ili9881c_5p99_720p_video_lane_config;
        panelstruct->paneltiminginfo    = &ares_l22_va_inx_ili9881c_5p99_720p_video_timing_info;
        panelstruct->panelresetseq = &ares_l22_va_inx_ili9881c_5p99_720p_video_reset_seq;
        panelstruct->backlightinfo = &ares_l22_va_inx_ili9881c_5p99_720p_video_backlight;
        if(ARES_L22_VA_INX_ILI9881C_5P99_720P_VIDEO_BIAS_IC_ARRAY == 0)
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = ares_l22_va_inx_ili9881c_5p99_720p_video_bias_ic_array;
        }
        panelstruct->lcd_bias_ic_info.num_of_lcd_bias_ic_list = ARES_L22_VA_INX_ILI9881C_5P99_720P_VIDEO_BIAS_IC_ARRAY;
        if(ARES_L22_VA_INX_ILI9881C_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY == 0)
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = ares_l22_va_inx_ili9881c_5p99_720p_video_backlight_ic_array;
        }
        panelstruct->lcd_backlight_ic_info.num_of_lcd_backlight_ic_list = ARES_L22_VA_INX_ILI9881C_5P99_720P_VIDEO_BACKLIGHT_IC_ARRAY;
        pinfo->labibb = &ares_l22_va_inx_ili9881c_5p99_720p_video_labibb;
        pinfo->mipi.panel_on_cmds  = ares_l22_va_inx_ili9881c_5p99_720p_video_on_command;
        pinfo->mipi.num_of_panel_on_cmds = ARRAY_SIZE(ares_l22_va_inx_ili9881c_5p99_720p_video_on_command);
        pinfo->mipi.panel_off_cmds  = ares_l22_va_inx_ili9881c_5p99_720p_video_off_command;
        pinfo->mipi.num_of_panel_off_cmds = ARRAY_SIZE(ares_l22_va_inx_ili9881c_5p99_720p_video_off_command);
        memcpy(phy_db->timing, ares_l22_va_inx_ili9881c_5p99_720p_video_timings, sizeof(ares_l22_va_inx_ili9881c_5p99_720p_video_timings));
        memcpy(panel_regulator_settings, ares_l22_va_inx_ili9881c_5p99_720p_video_regulator_setting, sizeof(ares_l22_va_inx_ili9881c_5p99_720p_video_regulator_setting));
        pinfo->pipe_type = ares_l22_va_inx_ili9881c_5p99_720p_video_mdp_pipe_type;
        phy_db->pll_type = ares_l22_va_inx_ili9881c_5p99_720p_video_dsi_pll_type;
        pinfo->mipi.signature = ares_l22_va_inx_ili9881c_5p99_720p_video_mipi_signature;
        lcdkit_config.lcd_platform   = &ares_l22_va_inx_ili9881c_5p99_720p_video_panel_platform_config;
        lcdkit_config.lcd_misc   = &ares_l22_va_inx_ili9881c_5p99_720p_video_panel_misc_info;
        lcdkit_config.lcd_delay     = &ares_l22_va_inx_ili9881c_5p99_720p_video_panel_delay_ctrl;
        pinfo->mipi.tx_eot_append = lcdkit_config.lcd_misc->tx_eot_append;
        pinfo->mipi.rx_eot_ignore = lcdkit_config.lcd_misc->rx_eot_ignore;
        phy_db->regulator_mode = lcdkit_config.lcd_misc->mipi_regulator_mode;
        lcdkit_config.backlight_cmds   = ares_l22_va_inx_ili9881c_5p99_720p_video_backlight_command;
        lcdkit_config.num_of_backlight_cmds   = ARRAY_SIZE(ares_l22_va_inx_ili9881c_5p99_720p_video_backlight_command);
        break;

    case DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL:
        panelstruct->paneldata    = &default_auo_otm1901a_5p2_1080p_video_default_panel_data;
        panelstruct->panelres     = &default_auo_otm1901a_5p2_1080p_video_default_panel_res;
        panelstruct->color        = &default_auo_otm1901a_5p2_1080p_video_default_color;
        panelstruct->videopanel   = &default_auo_otm1901a_5p2_1080p_video_default_video_panel;
        panelstruct->commandpanel = &default_auo_otm1901a_5p2_1080p_video_default_command_panel;
        panelstruct->state        = &default_auo_otm1901a_5p2_1080p_video_default_state;
        panelstruct->laneconfig   = &default_auo_otm1901a_5p2_1080p_video_default_lane_config;
        panelstruct->paneltiminginfo    = &default_auo_otm1901a_5p2_1080p_video_default_timing_info;
        panelstruct->panelresetseq = &default_auo_otm1901a_5p2_1080p_video_default_reset_seq;
        panelstruct->backlightinfo = &default_auo_otm1901a_5p2_1080p_video_default_backlight;
        if(DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_BIAS_IC_ARRAY == 0)
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_bias_ic_info.lcd_bias_ic_list = default_auo_otm1901a_5p2_1080p_video_default_bias_ic_array;
        }
        panelstruct->lcd_bias_ic_info.num_of_lcd_bias_ic_list = DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_BIAS_IC_ARRAY;
        if(DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_BACKLIGHT_IC_ARRAY == 0)
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = NULL;
        }
        else
        {
            panelstruct->lcd_backlight_ic_info.lcd_backlight_ic_list = default_auo_otm1901a_5p2_1080p_video_default_backlight_ic_array;
        }
        panelstruct->lcd_backlight_ic_info.num_of_lcd_backlight_ic_list = DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_BACKLIGHT_IC_ARRAY;
        pinfo->labibb = &default_auo_otm1901a_5p2_1080p_video_default_labibb;
        pinfo->mipi.panel_on_cmds  = default_auo_otm1901a_5p2_1080p_video_default_on_command;
        pinfo->mipi.num_of_panel_on_cmds = ARRAY_SIZE(default_auo_otm1901a_5p2_1080p_video_default_on_command);
        pinfo->mipi.panel_off_cmds  = default_auo_otm1901a_5p2_1080p_video_default_off_command;
        pinfo->mipi.num_of_panel_off_cmds = ARRAY_SIZE(default_auo_otm1901a_5p2_1080p_video_default_off_command);
        memcpy(phy_db->timing, default_auo_otm1901a_5p2_1080p_video_default_timings, sizeof(default_auo_otm1901a_5p2_1080p_video_default_timings));
        memcpy(panel_regulator_settings, default_auo_otm1901a_5p2_1080p_video_default_regulator_setting, sizeof(default_auo_otm1901a_5p2_1080p_video_default_regulator_setting));
        pinfo->pipe_type = default_auo_otm1901a_5p2_1080p_video_default_mdp_pipe_type;
        phy_db->pll_type = default_auo_otm1901a_5p2_1080p_video_default_dsi_pll_type;
        pinfo->mipi.signature = default_auo_otm1901a_5p2_1080p_video_default_mipi_signature;
        lcdkit_config.lcd_platform   = &default_auo_otm1901a_5p2_1080p_video_default_panel_platform_config;
        lcdkit_config.lcd_misc   = &default_auo_otm1901a_5p2_1080p_video_default_panel_misc_info;
        lcdkit_config.lcd_delay     = &default_auo_otm1901a_5p2_1080p_video_default_panel_delay_ctrl;
        pinfo->mipi.tx_eot_append = lcdkit_config.lcd_misc->tx_eot_append;
        pinfo->mipi.rx_eot_ignore = lcdkit_config.lcd_misc->rx_eot_ignore;
        phy_db->regulator_mode = lcdkit_config.lcd_misc->mipi_regulator_mode;
        lcdkit_config.backlight_cmds   = default_auo_otm1901a_5p2_1080p_video_default_backlight_command;
        lcdkit_config.num_of_backlight_cmds   = ARRAY_SIZE(default_auo_otm1901a_5p2_1080p_video_default_backlight_command);
        break;

    default:
        return false;
    }

    return true;
}

static uint16_t lcdkit_panel_init(uint16_t hw_id)
{
    uint16_t lcd_panel_id = DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL;
    hw_lcd_id_index lcd_hw_id = LCD_HW_ID_MAX;
    uint32_t i = 0;
    lcd_hw_id = (hw_lcd_id_index)hw_get_lcd_id(hw_id);

    dprintf(INFO,"lcd_panel_init lcd id = %d\n", lcd_hw_id);
    snprintf(lcd_id,sizeof(lcd_id), " huawei,lcd_panel_id = %X", lcd_hw_id);
    for (i = 0; i < ARRAY_SIZE(lcdkit_map); ++i) {
        if ((lcdkit_map[i].board_id == hw_id) && (lcdkit_map[i].gpio_id == lcd_hw_id)) {
            lcd_panel_id = lcdkit_map[i].lcd_id;
            break;
        }
    }

    return lcd_panel_id;
}

static void lcdkit_get_id_gpio(uint16_t hw_id, int* id0, int* id1)
{
    uint16_t i = 0;
    uint16_t def_id[] = {55,56};
    uint16_t id_gpio_grp[1][3] = {{0,0,0}};

    for (i = 0; i < 1; i++)
    {
        if (hw_id == id_gpio_grp[i][2])
        {
            *id0 = id_gpio_grp[i][0];
            *id1 = id_gpio_grp[i][1];
            return;
        }

    }

    if (i >= 1)
    {
        *id0 = def_id[0];
        *id1 = def_id[1];
    }

    return;
}


#endif /*_HW_LCD_PANELS__H_*/
