/* Copyright (c) 2013, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*-------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = 1.1
 *-----------------------------------------------------------------------*/

#ifndef _PANEL_V1_AUO_OTM1911A_7P12_1080P_VIDEO_H_

#define _PANEL_V1_AUO_OTM1911A_7P12_1080P_VIDEO_H_
/*-----------------------------------------------------------------------*/
/* HEADER files                                                          */
/*-----------------------------------------------------------------------*/
#include "panel.h"

#include "lcdkit_bias_ic_common.h"

#include "lcd_bl.h"

/*-----------------------------------------------------------------------*/
/* Panel configuration                                                   */
/*-----------------------------------------------------------------------*/
static struct panel_config v1_auo_otm1911a_7p12_1080p_video_panel_data = {
        "lcdkit_v1_auo_otm1911a_7p12_1080p_video", "dsi:0:", "auo_otm1911a_7p12_1080p_video", 
        10, 0, "DISPLAY_1", 0, 0, 60, 0, 0, 
        0, 1, 0, 0, 0, 0, 0, 1, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* Panel resolution                                                      */
/*-----------------------------------------------------------------------*/
static struct panel_resolution v1_auo_otm1911a_7p12_1080p_video_panel_res = {
        1080, 2244, 80, 80, 17, 0, 13, 10, 5, 0, 0, 0, 0, 0, 0, 0, 
        0, 0 
};

/*-----------------------------------------------------------------------*/
/* Panel color information                                               */
/*-----------------------------------------------------------------------*/
static struct color_info v1_auo_otm1911a_7p12_1080p_video_color = {
        24, 0, 0x00, 0, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* Panel on/off command                                                  */
/*-----------------------------------------------------------------------*/
static char v1_auo_otm1911a_7p12_1080p_video_on_cmd0[] = {
    0x02, 0x00, 0x29, 0xC0,
    0x00, 0x00, 0xFF, 0xFF};


static char v1_auo_otm1911a_7p12_1080p_video_on_cmd1[] = {
    0x04, 0x00, 0x29, 0xC0,
    0xff, 0x19, 0x11, 0x01,
   };


static char v1_auo_otm1911a_7p12_1080p_video_on_cmd2[] = {
    0x02, 0x00, 0x29, 0xC0,
    0x00, 0x80, 0xFF, 0xFF};


static char v1_auo_otm1911a_7p12_1080p_video_on_cmd3[] = {
    0x03, 0x00, 0x29, 0xC0,
    0xff, 0x19, 0x11, 0xFF};


static char v1_auo_otm1911a_7p12_1080p_video_on_cmd4[] = {
    0x02, 0x00, 0x29, 0xC0,
    0x00, 0xb0, 0xFF, 0xFF};


static char v1_auo_otm1911a_7p12_1080p_video_on_cmd5[] = {
    0x05, 0x00, 0x29, 0xC0,
    0xb3, 0x04, 0x38, 0x08,
    0xc4, 0xFF, 0xFF, 0xFF};


static char v1_auo_otm1911a_7p12_1080p_video_on_cmd6[] = {
    0x02, 0x00, 0x29, 0xC0,
    0x00, 0x00, 0xFF, 0xFF};


static char v1_auo_otm1911a_7p12_1080p_video_on_cmd7[] = {
    0x04, 0x00, 0x29, 0xC0,
    0xFF, 0xFF, 0xFF, 0xFF,
   };


static char v1_auo_otm1911a_7p12_1080p_video_on_cmd8[] = {
    0x11, 0x00, 0x05, 0x80};


static char v1_auo_otm1911a_7p12_1080p_video_on_cmd9[] = {
    0x29, 0x00, 0x05, 0x80};




static struct mipi_dsi_cmd v1_auo_otm1911a_7p12_1080p_video_on_command[] = {
{0x8, v1_auo_otm1911a_7p12_1080p_video_on_cmd0, 0x00},
{0x8, v1_auo_otm1911a_7p12_1080p_video_on_cmd1, 0x00},
{0x8, v1_auo_otm1911a_7p12_1080p_video_on_cmd2, 0x00},
{0x8, v1_auo_otm1911a_7p12_1080p_video_on_cmd3, 0x00},
{0x8, v1_auo_otm1911a_7p12_1080p_video_on_cmd4, 0x00},
{0xc, v1_auo_otm1911a_7p12_1080p_video_on_cmd5, 0x00},
{0x8, v1_auo_otm1911a_7p12_1080p_video_on_cmd6, 0x00},
{0x8, v1_auo_otm1911a_7p12_1080p_video_on_cmd7, 0x00},
{0x4, v1_auo_otm1911a_7p12_1080p_video_on_cmd8, 0x64},
{0x4, v1_auo_otm1911a_7p12_1080p_video_on_cmd9, 0x00}
};
#define V1_AUO_OTM1911A_7P12_1080P_VIDEO_ON_COMMAND 10


static char v1_auo_otm1911a_7p12_1080p_video_off_cmd0[] = {
    0x28, 0x00, 0x05, 0x80};


static char v1_auo_otm1911a_7p12_1080p_video_off_cmd1[] = {
    0x10, 0x00, 0x05, 0x80};


static char v1_auo_otm1911a_7p12_1080p_video_off_cmd2[] = {
    0x02, 0x00, 0x29, 0xC0,
    0x00, 0x00, 0xFF, 0xFF};


static char v1_auo_otm1911a_7p12_1080p_video_off_cmd3[] = {
    0x04, 0x00, 0x29, 0xC0,
    0xFF, 0x19, 0x11, 0x01,
   };


static char v1_auo_otm1911a_7p12_1080p_video_off_cmd4[] = {
    0x02, 0x00, 0x29, 0xC0,
    0x00, 0x90, 0xFF, 0xFF};


static char v1_auo_otm1911a_7p12_1080p_video_off_cmd5[] = {
    0x02, 0x00, 0x29, 0xC0,
    0xb3, 0x34, 0xFF, 0xFF};




static struct mipi_dsi_cmd v1_auo_otm1911a_7p12_1080p_video_off_command[] = {
{0x4, v1_auo_otm1911a_7p12_1080p_video_off_cmd0, 0x00},
{0x4, v1_auo_otm1911a_7p12_1080p_video_off_cmd1, 0x78},
{0x8, v1_auo_otm1911a_7p12_1080p_video_off_cmd2, 0x00},
{0x8, v1_auo_otm1911a_7p12_1080p_video_off_cmd3, 0x00},
{0x8, v1_auo_otm1911a_7p12_1080p_video_off_cmd4, 0x00},
{0x8, v1_auo_otm1911a_7p12_1080p_video_off_cmd5, 0x00}
};
#define V1_AUO_OTM1911A_7P12_1080P_VIDEO_OFF_COMMAND 6


static struct command_state v1_auo_otm1911a_7p12_1080p_video_state = {
        0, 0 
};

/*-----------------------------------------------------------------------*/
/* Command mode panel                                                    */
/*-----------------------------------------------------------------------*/
static struct commandpanel_info v1_auo_otm1911a_7p12_1080p_video_command_panel = {
        0, 1, 1, 0, 0, 0x2c, 0, 0, 0, 1, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* Video mode panel                                                      */
/*-----------------------------------------------------------------------*/
static struct videopanel_info v1_auo_otm1911a_7p12_1080p_video_video_panel = {
        1, 0, 0, 0, 1, 1, 2, 0, 0x9 
};

/*-----------------------------------------------------------------------*/
/* Lane configuration                                                    */
/*-----------------------------------------------------------------------*/
static struct lane_configuration v1_auo_otm1911a_7p12_1080p_video_lane_config = {
        4, 0, 1, 1, 1, 1, 0 
};

/*-----------------------------------------------------------------------*/
/* Panel timing                                                          */
/*-----------------------------------------------------------------------*/
static const uint32_t v1_auo_otm1911a_7p12_1080p_video_timings[]= {
        0xe6, 0x38, 0x26, 0x00, 0x68, 0x6e, 0x2a, 0x3c, 0x44, 0x03, 0x04, 0x00 
};

static struct panel_timing v1_auo_otm1911a_7p12_1080p_video_timing_info = {
        0, 4, 0x0E, 0x36 
};

/*-----------------------------------------------------------------------*/
/* Panel reset sequence                                                  */
/*-----------------------------------------------------------------------*/
static struct panel_reset_sequence v1_auo_otm1911a_7p12_1080p_video_reset_seq = {
    { 1, 0, 1, }, { 10, 10, 10, }, 2
};

/*-----------------------------------------------------------------------*/
/* Backlight setting                                                     */
/*-----------------------------------------------------------------------*/
static struct backlight v1_auo_otm1911a_7p12_1080p_video_backlight = {
        0, 15, 4095, 1, 1, 0 
};

/*-----------------------------------------------------------------------*/
/* Labibb setting                                                        */
/*-----------------------------------------------------------------------*/
static struct labibb_desc v1_auo_otm1911a_7p12_1080p_video_labibb = {
        1, 1, 5500000, 5500000, 5500000, 5500000, 3, 0, 3, 1, 0 
};

/*-----------------------------------------------------------------------*/
/* turn on backlight delay                                               */
/*-----------------------------------------------------------------------*/
int v1_auo_otm1911a_7p12_1080p_video_mdp_pipe_type  = MDSS_MDP_PIPE_TYPE_RGB;

int v1_auo_otm1911a_7p12_1080p_video_dsi_pll_type  = DSI_PLL_TYPE_THULIUM;

int v1_auo_otm1911a_7p12_1080p_video_mipi_signature  = 0xffff;

static const uint32_t v1_auo_otm1911a_7p12_1080p_video_regulator_setting[]= {
        0x1d, 0x1d, 0x1d, 0x1d, 0x1d 
};

/*-----------------------------------------------------------------------*/
/* platform Config                                                       */
/*-----------------------------------------------------------------------*/
static struct lcdkit_platform_config v1_auo_otm1911a_7p12_1080p_video_panel_platform_config = {
        0, 0, 0, 0, 0x10002, 0x10000, 0x200, 0x20, 0, 0, 0, 53, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5500000, 5500000, 0, 0, 0, 0, 0, 
        0, 0, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* misc Information                                                      */
/*-----------------------------------------------------------------------*/
static struct lcdkit_misc_info v1_auo_otm1911a_7p12_1080p_video_panel_misc_info = {
        0, 0, 0, 1, 0x01, 0x01, 0x01, 0, 1, 0, 1, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* delay ctrl                                                            */
/*-----------------------------------------------------------------------*/
static struct lcdkit_delay_ctrl v1_auo_otm1911a_7p12_1080p_video_panel_delay_ctrl = {
        0, 10, 0, 3, 6, 0, 3, 5, 0, 0, 0, 0, 20, 0, 50 
};

static char v1_auo_otm1911a_7p12_1080p_video_backlight_cmd0[] = {
    0x03, 0x00, 0x29, 0xC0,
    0x51, 0x00, 0x00, 0xFF};




static struct mipi_dsi_cmd v1_auo_otm1911a_7p12_1080p_video_backlight_command[] = {
{0x8, v1_auo_otm1911a_7p12_1080p_video_backlight_cmd0, 0x00}
};
#define V1_AUO_OTM1911A_7P12_1080P_VIDEO_BACKLIGHT_COMMAND 1



static struct lcd_bias_voltage_info * v1_auo_otm1911a_7p12_1080p_video_bias_ic_array[0];
 
#define V1_AUO_OTM1911A_7P12_1080P_VIDEO_BIAS_IC_ARRAY 0


static struct backlight_ic_info * v1_auo_otm1911a_7p12_1080p_video_backlight_ic_array[0];
 
#define V1_AUO_OTM1911A_7P12_1080P_VIDEO_BACKLIGHT_IC_ARRAY 0


#endif /*_PANEL_V1_AUO_OTM1911A_7P12_1080P_VIDEO_H_*/
